- app.py
- repository_service_tuf_worker/__init__.py
- repository_service_tuf_worker/__version__.py
- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/services/__init__.py
- repository_service_tuf_worker/services/keyvault/__init__.py
- repository_service_tuf_worker/services/keyvault/local.py
- repository_service_tuf_worker/services/storage/__init__.py
- repository_service_tuf_worker/services/storage/local.py
- setup.py
- tests/__init__.py
- tests/unit/__init__.py
- tests/unit/test_app.py
- tests/unit/tuf_repository_service_worker/__init__.py
- tests/unit/tuf_repository_service_worker/services/__init__.py
- tests/unit/tuf_repository_service_worker/services/keyvault/__init__.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tests/unit/tuf_repository_service_worker/services/storage/__init__.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Update Copyright to VMware Inc.
Signed-off-by: Kairo de Araujo <kairo@kairo.eti.br>
> Update Copyright to VMware Inc

- .github/workflows/cd.yml
Fixes the release CD pipeline with GH Registry.
> fix: Release CD pipeline

- repository_service_tuf_worker/__version__.py
Release Container Image v0.0.1a2
> Release v0.0.1a2

- repository_service_tuf_worker/__version__.py
> Release v0.0.1a3

- .github/workflows/ci.yml
- docker-compose.yml
Make API docker image public in docker-compose.yml.
Close #55 
> Make API docker image public in docker-compose.yml

- Makefile
Synchronize changes in Makefile with API
> Synchronize changes in Makefile with API

- repository_service_tuf_worker/__init__.py
- repository_service_tuf_worker/__version__.py
- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/models/__init__.py
- repository_service_tuf_worker/models/targets/__init__.py
- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/models/targets/models.py
- repository_service_tuf_worker/models/targets/schemas.py
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/services/__init__.py
- repository_service_tuf_worker/services/keyvault/__init__.py
- repository_service_tuf_worker/services/keyvault/local.py
- repository_service_tuf_worker/services/storage/__init__.py
- repository_service_tuf_worker/services/storage/local.py
- setup.py
- tests/__init__.py
- tests/unit/__init__.py
- tests/unit/test_app.py
- tests/unit/tuf_repository_service_worker/__init__.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/services/__init__.py
- tests/unit/tuf_repository_service_worker/services/keyvault/__init__.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tests/unit/tuf_repository_service_worker/services/storage/__init__.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_repository.py
- Update all the Copyright to 2022-2023
Component Interoperability Matrix
* RSTUF API >= v0.0.2a1
> Release v0.0.2a1

- repository_service_tuf_worker/__version__.py
* Component Interoperability Matrix
- RSTUF API >= v0.1.0a1
> Release v0.1.0a1

- repository_service_tuf_worker/__version__.py
- Fixes to previous alpha version (v0.1.0a1)
> Release v0.1.0a2

- .github/workflows/cd.yml
- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
- Makefile
- docker-compose.yml
- docs/source/guide/Docker_README.md
Rename `ghcr.io/vmware` to `ghcr.io/repository-service-tuf`
> Rename GH infrastrucure

- repository_service_tuf_worker/__version__.py
* Component Interoperability Matrix
- RSTUF API >= v0.2.0a1
> Release v0.2.0a1

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Add the _bump_and_persist() helper which combines:
- bump_expiry
- bump_version
- sign
- persist
This will help us prevent mistakes when using those functions as sometimes they do happen.
As for example, something that I noticed is that we didn't pass the targets name here:
https://github.com/repository-service-tuf/repository-service-tuf-worker/blob/355c0cdda9c5f6cd808b6ab7ee5795e956aa4c4e/repository_service_tuf_worker/repository.py#L853
Close #262
> Repository: add a common helper of 4 functions

- Pipfile.lock
- repository_service_tuf_worker/repository.py
- requirements-dev.txt
- requirements.txt
- tests/unit/tuf_repository_service_worker/test_repository.py
Add PUT /api/config endpoint to update settings
The API implementation is here: https://github.com/repository-service-tuf/repository-service-tuf-api/pull/387
Close  #297.
> Add task "update_settings" in Repository

- repository_service_tuf_worker/__version__.py
Prepare release according with [v0.7.0b1 milestone](https://github.com/repository-service-tuf/repository-service-tuf-worker/milestone/9)
> Prepare release 0.7.0b1

- .github/workflows/cd.yml
This will ask a maintainer to approve the release in order to validate details before pushing to the GHCR.
> Add the Maintainers approval to release

- .pre-commit-config.yaml
- repository_service_tuf_worker/repository.py
Fix the precommit error: tox: error: unrecognized arguments: <changed files>
Update the pre-commit versions
> Fix precommit for `tox -e requirements`

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
Prepare functional tests scripts for md update.
Fixing issue https://github.com/repository-service-tuf/repository-service-tuf-worker/actions/runs/6746697951/job/18343110442?pr=355#step:5:950
> Prepare functional tests scripts for md update

- Pipfile.lock
- requirements-dev.txt
- requirements.txt
The current workflow to update the PR is failing.
I'm submitting the PR to fix the vulnerability about PyArrow CVE-2023-47248
> Update Python requirements

- docs/source/devel/repository_service_tuf_worker.rst
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Enhance the consistency of Task Results in our codebase.
This PR creates a consistent data structure for Task responses.
Fixes #351
> refactoring: update Task response data structure

- repository_service_tuf_worker/__version__.py
> Release v0.12.0b1

- .github/workflows/publish_container.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
Add support to build images linux/arm64.
Related: repository-service-tuf/repository-service-tuf#615
> feature: support container image linux/arm64

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This change is in sync with changes happening in the RSTUF API.
Reasons for this change and API pr you could see here:
https://github.com/repository-service-tuf/repository-service-tuf-api/pull/551
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
> Address bootstrap payload changes

- docs/source/devel/design.rst
- docs/source/devel/index.rst
- docs/source/guide/Docker_README.md
Update guide and devel about KeyVault reference
> docs: Update guide and devel about KeyVault

- repository_service_tuf_worker/__version__.py
> release: v0.17.0b1

- .github/workflows/cd.yml
We are not supporting MySQL officially in the current version.
> Remove MySQL from CD.yml pipeline

- repository_service_tuf_worker/__version__.py
Prepare version for RSTUF release v1.0.0rc1
> Prepare release v1.0.0rc1

- MAINTAINERS.rst
> Update maintainers emails
