- .github/workflows/ci.yml
The coverage must run in the push to main branch.
It will give the accurated stats in the Codecov
Remove the token for codecov
Closes #78
> Fix coverage stats

- .github/workflows/cd.yml
- Makefile
- README.rst
Implement a new continuous delivery for component container images.
Remove the complexity of approval (by environment) once it is an unavailable feature.
Updates the README.rst to give the link to the image usage documentation.
Closes #79 
Closes #63 
> Implements new CD

- repository_service_tuf_worker/repository.py
The RSTUF worker is deprecating `add_initial_metadata` and replacing by `bootstrap`.
This patch removes part of the code that was used by the deprecated function `add_initial_metadata`.
That was removed from the repository-service-tuf-api issue #108
See PR #129 https://github.com/vmware/repository-service-tuf-api/pull/129
Closes #57 
[Edited]
Signed-off-by: juniorlpa <luiz.pandradejr@gmail.com>
> Removes deprecated repository metadata.

- Makefile
- tox.ini
Fixes #73
The changes in this pr are as follows:
1. update the `pipenv` command in `Makefile`
2. update the `requirements` files content
3. add a tox ci test where we check if there is a new dependency or version of a dependency that should be added to any of the requirements files.
PS: These changes in this pr were first discussed here: https://github.com/vmware/repository-service-tuf-api/pull/124
> Update pipenv commands and add requirements tox run

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/publish_docker_dev.yml
- .github/workflows/test_docker_build.yml
Fixes: #81 #82
Pines hash for GitHub actions in workflow yml files.
This will allow dependabot to update our actions by using hashes
as well.
I checked the latest stable versions for each of our action dependencies and got the commit hashes.
I have done a check for security advisories for each of the actions, but haven't found any.
The versions I have used for each of the actions are as follows:
- [actions/checkout v3.1.0](https://github.com/actions/checkout/releases/tag/v3.1.0)
- [actions/setup-python v4.3.0](https://github.com/actions/setup-python/releases/tag/v4.3.0)
- [docker/setup-qemu-action v2.1.0](https://github.com/docker/setup-qemu-action/releases/tag/v2.1.0)
- [docker/setup-buildx-action v2.2.1](https://github.com/docker/setup-buildx-action/releases/tag/v2.2.1)
- …
> Pin hashes for GitHub actions in workflow yml files

- .github/workflows/cd.yml
- Dockerfile
Add the release in the GitHub repository Releases.
It will give users more clear releases notes as the GHCR does not have a detailed release notes.
- Dockerfile build is missing upgrade pip and can raise error
> Add release to GH repository releases

- Makefile
- Pipfile
- Pipfile.lock
- requirements-dev.txt
- requirements.txt
It is a workaround for `securesystemslib` compatibility with rstuf-worker.
The securesystemslib version 0.25.0 is not working with rstuf-worker v0.0.1a2.
Workaround for bug #118
(Fix `make purge`, wrong container image reference)
> workaround: fix sslib compatiblity

- .github/workflows/cd.yml
When a release is trigged, it uses the functional tests from vmware/repository-service-tuf (umbrella repository).
The release is build/published if the functional tests are ok.
Closes #117 
> build: functional tests before release

- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_repository.py
In repository_service_tuf_worker/interfaces.py:
Made coverage ignore (# pragma: no cover) the interfaces' methods that have exceptions in the abstract classes as they will never be raised (a TypeError will be raised instead if an abstract method is not implemented).
The exceptions could be substituted with the "pass" keyword in IStorage(StorageBackendInterface) class, but to keep compatibility with the securesystemslib/storage.py implementation of StorageBackendInterface of the securesystemslib package, we keep it as is.
In tests/unit/tuf_repository_service_worker/services/storage/test_local.py:
- Changed default stub value of version. Stubbed tests for LocalStorage.get should not have default stub for version equal to 1, because that's also the default value when a ValueError exception …
> Improve unit test coverage

- Makefile
- docker-compose.yml
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
It adds a new field in the responses for the tasks received or updated by the rstuf worker.
This field helps to the requesters manage the tasks based on date time
> feat: add last_update on tasks information

- app.py
- docs/source/guide/Docker_README.md
The current custom Redis configuration for the RSTUF Worker container doesn't work correctly.
The backend result custom port is not corrrectly parsed for the callbacks (signals) and in the default Celery Backend
> fix: custom redis configuration for the container

- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
Refactored test_crud.py with more clear variables name.
Mocking the DB requires multiple sub-functions to be also mocked. This commit uses a more readable naming for these mocks.
Closes: #157 
> test: refactored test_crud variables name

- .github/workflows/ci.yml
- tox.ini
I noticed we run build for python3.9 when we say we support only python3.10 onwards.
That's why it seemed unnecessary that we are testing for python3.9.
Related to:
- https://github.com/vmware/repository-service-tuf-api/pull/222
- https://github.com/vmware/repository-service-tuf-cli/pull/172
> Remove python3.9 in .github/workflows/ci.yml

- repository_service_tuf_worker/models/targets/crud.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
This commit doesn't change the logic of the implementations that uses this specific crud, just get the role names ordered by the delegated hash bin role names.
In the case of debugging, it will help to understand the flow.
Closes #117
> chore: query unpublished role names ordered

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
As described in the feature https://github.com/vmware/repository-service-tuf/issues/28 we no longer need the BIN role.
We can remove all mentions and usages of it and instead use the top-level targets role to do its purpose and use succinct hash bin delegation.
It will be wise if we first merge:
- https://github.com/vmware/repository-service-tuf-api/pull/226
- https://github.com/vmware/repository-service-tuf-cli/pull/175
Close #165
> Remove the BIN role from RSTUF Worker

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- requirements-dev.txt
- tox.ini
To achieve the OpenSSF Best Practices badge, we need to implement the static code analysis tool.
This commit adds the `bandit` to the RSTUF Worker.
> Add bandit to the pre-commit

- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/services/storage/local.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
Fixes the Local storage service write permission implementation.
The Local Storage files don't require restricted permission (0o600) as the local storage writes publicly readable metadata files.
Only Private keys require security restriction permission.
Closes #183
> fix: Local storage service write permission

- repository_service_tuf_worker/interfaces.py
RSTUF is MIT licensed.
Removed some wrong entry in the file.
> fix: remove wrong entry in the file

- app.py
- repository_service_tuf_worker/repository.py
- tests/unit/test_app.py
There is no point in refreshing the repository settings when we launch
a subtask from a main task that has already updated the repository
settings.
That's what happens when we launch a new "publish_targets" from the
"repository._send_publish_targets_task()" function.
By default this optional argument "refresh_settings" is false to
make sure we don't break any of the current components launching a
worker task.
Close https://github.com/vmware/repository-service-tuf-worker/issues/178
> Skip refresh settings on subtasks

- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This improves the performance of updating Targets in the SQL DB.
Previously, we used to update the targets one by one in the DB and this commit made it in bulk.
In publishing new targets, we used to persist in the hashed bins with new targets to the backend storage, update the snapshot, and update the timestamp followed by the targets one by one in the SQL DB.
The last step was improved doing the update of all published targets at once.
Closes #176
> chore: improve performance updating Targets in DB

- app.py
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
When adding/removing targets, it triggers a new job to publish the
targets.
This subtask could fail for some reason, and we don't monitor it.
This commit adds the monitoring for this task and will give details
to the user once it fails the parent task (add/remove targets).
Closes #190
The monitoring is done in the `_update_task` as part of checks.
As discussed in issue https://github.com/vmware/repository-service-tuf-worker/issues/175, we removed the automatic job that
publishes targets every minute.
The publish targets are done to persist in the RSTUF Worker backend
storage of the updated metadata with the new targets.
1. We will give full control over the failure to add/remove targets
to the user. They can decide to reprocess the entire flow (add/remove
targets), or they can trigger …
> Monitor publish tasks sub task and remove automatic job publishing targets

- .pre-commit-config.yaml
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/services/keyvault/local.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tox.ini
Add configuration settings in LocalKeyVault for the online key that
will be used for "timestamp", "snapshot", "targets"  and "bin-n" roles.
That will allow us to load the online key instead of generating it
which is in line with what we want when we support more key vaults.
It's planned that if the user doesn't provide a path to the online key
as recommended we will generate an online key for him.
Additionally, add missing type annotations for the interfaces.
Close https://github.com/vmware/repository-service-tuf-worker/issues/169
> Add LocalKeyVault configuration settings for the online key

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
- tox.ini
There is a new field that will be introduced in the RSTUF add and remove
API calls named "publish_targets".
This flag can be used by users to tell whether to start a subtask
publishing the latest targets changes.
By default, this flag will be enabled.
Close #198 
> Accept "publish_targets" in add/remove targets

- repository_service_tuf_worker/repository.py
This deletes text referring to Apache License in repository.py.
Signed-off-by: Enyinna Ochulor <eochulor@vmware.com>
> Removes The Apache License

- .github/workflows/cd.yml
- .github/workflows/publish_container.yml
This PR introduces a change in the `cd.yml` and adds the `publish_container.yml  Workflow.
We release our components versions using the tags `v*` The process of release has two steps:
1) Run the functional tests (FT) using the component to be released `v*` tag (from `main` branch) against the latest releases of the components.
2) If the (FT) finishes successfully, the `cd.yml` releases the new Docker Image GitHub Registry and adds it to our Releases page in Github. (Python package in case of the CLI).
If step 1 fails, the release breaks the compatibility with the current release.
The problem we are solving is how to release a new version when it breaks the compatibility.
This PR adds the workflow dispatch option for releases. The maintainers can now go to the Actions > CD > Run Workflow, …
> Flexible maintainer CD Workflow

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This calls bump_online_role to update snapshot, timestamp, target, and bins during a bootstrap operation. This way, the updates don't have to wait for the automatic check to update those values.
Closes #26
> Update Metadata During Bootstrap

- app.py
- repository_service_tuf_worker/__init__.py
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test__init__.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Currently, repository.py and app.py use the worker and repository settings setup in repository_service_tuf_worker/__init__.py The way they are configured now (without a function/class directly in the module) means that when for the first time anything is imported from repository_service_tuf_worker/ it results in configuring the worker and repository settings.
As a side effect, this means that even if something is imported from repository_service_tuf_worker/ later this won't cause a new set of worker and repository settings to be set up.
This becomes a problem for our tests where in the test_repository.py and test_app.py modules we want to make sure that we have a new set of settings.
That is important because the worker and repository settings define the behavior of the …
> Make tests repository and app tests independent

- .github/workflows/cd.yml
It gives the flexibility to release or re-release new container images without adding them as a latest tag.
Reference implementation:
https://github.com/vmware/repository-service-tuf-api/pull/284
> Add the release tag latest as optional.

- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/services/storage/local.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Make sure that LocalStorage.get() and IStorage.get() return the same
type: Metadata[T].
Currently, the LocalStorage.get() behaves like a context manager and
returns "BufferedReader" without a good reason for that and doesn't
follow what the interface has defined as a return type - Metadata[T].
Additionally, I am removing repository._load() as we are making a mistake in passing
self.storagebackend() as an argument to "Metadata.from_file()" where it
expects an object from the type securesystemslib.StorageBackendInterface
but our self._storagebackend() doesn't implement that interface.
Finally, there are more checks made inside LocalStorage.get()
and this will allow us to be more flexible when we introduce other
storage services.
> Update LocalStorage.get() to follow the interface & remove _load()

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Generate metadata for `Targets`, `Snapshot`, `Timestamp` and succinct delegated roles (`bins`) using online key during the bootstrap process.
This implementation is part of bootstrap simplification.
The Worker will receive only the root metadata and build all the roles that uses the online key.
Closes #168.
> Generate online roles metadata during bootstrap

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
As RSTUF now uses the online key for Targets role, in this commit, we add the bump of Targets role.
* It renames the bump_bins_roles to bump_targets_roles
* It now bumps all Targets roles types, including Targets and its Delegated Roles bins
It guarantees that the target's role is automatically bumped before expiring, as we do for all roles which use online keys.
Closes #254
> fix: Add bump for Targets role

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This fix an old call using refactored `bump_bin_roles`
> hotfix: wrong call after refactoring bump_bins_roles

- repository_service_tuf_worker/__version__.py
Implements a hotfix for the automated bumping versions for the expired metadata (roles that uses online keys)
> Release v0.1.0a3

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/cd.yml
- README.rst
- app.py
- docs/source/devel/index.rst
- docs/source/devel/known_issues.rst
- setup.py
It is part of the process moving RSTUF to OpenSSF organization.
> Move RSTUF to github.com/repository-service-tuf

- docker-compose.yml
- docs/source/guide/Docker_README.md
- entrypoint-dev.sh
- entrypoint.sh
- tox.ini
This commit documents and move `RSTUF_WORKER_ID` environment variable as optional.
The `RSTUF_WORKER_ID` is now optional and by default uses the container hostname.
This enables RSTUF user spin multiple replicas using for example kubernetes without dealing to generate multiple environment variables.
Closes #260
> RSTUF_WORKER_ID as optional container parameter

- docs/source/guide/Docker_README.md
Add the mention about the secrets standard adopted by RSTUF. RSTUF requires user to mount the secrets volume in `/run/secrets` path.
> Update container docs about secrets

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This commit implements two new functionalities in the Repository
* `write_repository_settings`
This method has the functionality to write settings values to the Repository settings. The repository settings uses Dynaconf configured to the Redis Server (`RSTUF_REDIS_SERVER`). This configuration is shared accross the Workers (if multiple).
This function receives a key and value and stores it to the Redis server
* `save_settings`
Uses the `write_repository_settings` to save all configuration from the Repository, which is a defined payload from the RSTUF API service. this function also requires the root TUF metadata.
settings payload:
```json
{
"expiration": {
"root": 365,
"targets": 365,
"snapshot": 1,
"timestamp": 1,
"bins": 1
},
"services": {
"targets_base_url": …
```
> Repository Settings write implementation

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This commit implements the metadata rotation.
This feature allows RSTUF administrators to rotate the root metadata and the online keys, which requires signing with offline keys (root keys).
Closes #221
> feature: Metadata/key rotation

- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This commit improves and gives users more flexibility to configure the SQL server on RSTUF Worker.
The user can now use secrets instead of plain text to configure the SQL server password.
The user is still able to use the previous configuration.
Closes #231
> Improve the SQL worker container configuration

- docker-compose.yml
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/services/keyvault/local.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tox.ini
This commit proposes a new design to the LocalKeyVaul, a KeyVault service.
This commit gives the flexibility to the user to configure multiple online keys.
RSTUF supports a single online key. However, multiple online keys configuration must be required during RSTUF operation to reduce service disruption.
The most common use case is Online Key rotation.
A user who wants to rotate the key must update all the RSTUF Workers with the current and new keys. In that way, the RSTUF Workers will always find out which key matches the online key configured in the TUF root metadata.
This proposal will change the LocalKeyVault to use two environment variables:
`RSTUF_LOCAL_KEYVAULT_PATH`, which maps to the container volume mapped to the container running. This will also be used to support the key as a …
> LocalKeyVault KeyVault Service Enhancement

- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/services/keyvault/local.py
- Fix keyvault misspelled `KEYVAYLT` in docstrings
- Fix LocalKeyVault example in the Docker readme using old environment settings
> fix keyvault misspelled and Docker README

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
It aligns the process name with the function name of the other
components (API and CLI).
Renames the function from `metadata_rotation` to `metadata_update`.
Add the `metadata_rotation` function, which calls the
`metadata_update` but also gives a warning and warning logs.
It gives compatibility for users using the RSTUF API v2.3.0b1 with
RSTUF Worker until version >= v0.4.0b1 > v1.0.0.
Fix the unit tests and add an extra test to check the deprecation warning.
Add support to multiple metadata rotation types 
Even now, the RSTUF process uses Online Key only for Root Metadata; this
PR improves the Metadata Update process to support the future
multiple Metadata types.
This also makes more clear with the helper function, where all the Root
Metadata process.
Add/extend root check in a helper …
> Refactoring metadata update

- docs/diagrams/repository-service-tuf-worker-C2.puml
Fix the diagrams that uses the plantuml awslib
The awslib changed some of their icons which is causing error in the plantuml build
```
plantuml -o ../source/_static/ -tpng docs/diagrams/*.puml
Error line 27 in file: docs/diagrams/repository-service-tuf-worker-C2.puml
Some diagram description contains errors
make: *** [Makefile:21: docs] Error 200
```
> Fix diagrams causing error in Umbrella Docs

- entrypoint-dev.sh
- entrypoint.sh
This check fails the container start in case the Postgres has a misconfiguration or it is not healthy.
The current version of RSTUF will not handle it if the database migrations (`allambic`) fail, and the container will stay up and running.
The failure will be noticed only the user does one action, for example, bootstrap, add a target etc.
The RSTUF user/admin needs to ensure the container is running before use.
Example:
If the user configures the RSTUF Worker with the wrong credentials to Postgres and starts the RSTUF Worker, it will fail the database migrations -- not creating the initial database -- and the container will continue up and running.
When the user tries a bootstrap, it will fail due to the credential.
```shell
Starting online bootstrap
Bootstrap status: ACCEPTED …
```
> Exit the container if database is not ready

- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test_repository.py
With this pr I fix two bugs:
- bug where two bin versions will be published on every bump_online_roles call or on every automatic bump of online roles because of expiry
- bug where a bin/bins doesn't contain target files and it couldn't be updated because of that in update_snapshot
Closes #328 #330
> Fix twice bumping bins and no automatic bump

- .github/workflows/cd.yml
Fix the RSTUF Worker container image release tag.
The tag `latest` wasn't being added to the releases confusing the users running old versions.
> Fix RSTUF Worker container image release tag

- repository_service_tuf_worker/repository.py
- tests/unit/conftest.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This commit implements a standardized task result for RSTUF Worker.
This implementation gives the user a more consistent task result, making it easy to parse the tasks and implement flows using the RSTUF in general. For example, to create call back and task management for RSTUF Operations such as adding artifacts, removing, publishing, signing metadata, etc.
The task results have the following standard.
```python
{
"task_id": "be930844ee0f4396b86a08de90117680",
"state": "SUCCESS",    # Celery Task State
"result": {  # Task Result
"task": "update_settings",  # Task requested
"status": True,  # Task status
"last_update": "2023-08-10T08:11:32.477608",
"details": {
"message": "Update settings succeeded",  # General message
"error":  "Error detail"  # In case of state `False`
"Any": "Any  # …
```
> Standardize RSTUF Worker tasks result

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
It fixes the `_update_snapshot` to update the Snapshot Meta with the latest versions.
It was missing in the loop to add the latest role json version. It also improves the UT to check the changes in the snapshot version and the meta updates to avoid regression.
Closes #353
> fix: Automatic bump online roles, meta update

- repository_service_tuf_worker/repository.py
As we have discussed with Kairo we prefer if enum values are upper case the same way as constants are:
https://peps.python.org/pep-0008/#constants
and the same way all of our enums are until now.
> Rename enum values to follow convention

- tests/unit/tuf_repository_service_worker/test_repository.py
Fixes a few instances of test Root objects being incorrectly wrapped in Root objects, when they should be wrapped in Metadata objects.
Additionally, uses default values for Root.version and Metadata.signatures, instead of passing the same values explicitly.
Note that neither the mistakes nor their fix affect the test results, because the test doesn't care about the signature wrapper (*if it doesn't quack, it can still be a duck*).
Fixing this still seems reasonable.
> Fix incorrect test data in test_sign_metadata*

- tests/unit/tuf_repository_service_worker/test_repository.py
This commit is a follow-up to the PR #354 
It adds a test to check if the `timestamp` version is updated to avoid regression on changes in RSTUF.
> Add in UT a check if timestamp version is updated

- Makefile
**Update docker-compose commands to use "docker compose"**
This PR updates the usage of Docker Compose commands in Makefile to use the new "docker compose" syntax introduced in Docker Compose. 
The new syntax offers improved consistency and ease of use.
Changes made:
- Replaced occurrences of "docker-compose" with "docker compose".
Closes #342 
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).
> Update docker-compose commands by docker compose

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
This will add support to the new `DELETE /api/v1/metadata/sign endpoint`.
Check https://github.com/repository-service-tuf/repository-service-tuf-api/pull/432.
Fixes: #368 
> feat: Add a new delete_sign_metadata task

- .github/workflows/publish_container.yml
In this commit, we have improved the `publish_container.yml` workflow in the repository to provide additional clarity and permissions for its usage. This workflow plays a critical role in our Continuous Deployment (CD) process when a new `vX.Y.Z` tag is pushed, primarily performed by RSTUF maintainers.
1. **Write Permissions**: We have added write permissions to the `publish_container.yml` workflow. This ensures that only authorized individuals, such as RSTUF maintainers, can trigger this workflow.
2. **Usage Clarification**: We have clarified the multiple use cases of this workflow: - It is triggered during the release process when a new version tag (`vX.Y.Z`) is pushed. - It is used when a pull request (PR) is approved by RSTUF maintainers, as specified in `review-approved.yml`.
3. …
> Add write packages in `publish_container` workflow

- .github/workflows/publish_container.yml
- .github/workflows/review-approved.yml
This commit implements the Functional Tests when a PR is approved by a reviewer.
It improves our checks on new changes in the RSTUF Worker, avoiding breaking compatibility and later discovery during the release.
It covers any PR submitted, including the build PRs for updating the dependencies.
It uses the Worker version from the PR source code after the merge will also be used as `dev` tab.
> Introduces the FT when PR is approved

- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/services/keyvault/local.py
- repository_service_tuf_worker/services/storage/local.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_interfaces.py
- The old `repository.refresh_settings` handling the IServices
configuration was moved to the `interfaces`
- Now the way to import a `I{Services}` uses the dynaconf directly
- Adds better error messages for the wrong configuration
- Support a service has one setting with multiple environment variables
what is helpful for third-party libraries that use environment vars
> RSTUF Interface refactoring (IServices)

- app.py
- repository_service_tuf_worker/repository.py
- tests/unit/test_app.py
Superceeds: #390.
Currently, we are calling refresh_settings many times:
1. a couple of times when we set up SQL, Storage Backend, KeyVault and timeout when initializing MetadataRepository
2. once per task we call refresh_settings
In a discussion with Kairo we reevaluated this design and realized that if there is a change that needs to be made then the user needs to update the environmental variables which will require restart of all worker containers and as a result refresh_settings will be called for sure. This means that us calling refresh_settings on each task or during MetadataRepository initialization is redundant as nothing can be changed from the settings without the requirement to restart the containers, otherwise an error will be raised.
> Stop calling refresh_settings on each task

- .github/workflows/cd.yml
- .github/workflows/functional-tests.yml
- .github/workflows/review-approved.yml
- .gitignore
- Makefile
- README.rst
- docker-compose-redis.yml
- tox.ini
* Deploys the RSTUF using Worker image from source code
* Uses two different deployment:
- Local Services with RabbitMQ as broker (message queue)
- Local Service with Redis as broker (message queue)
* Uses the RSTF Umbrella `run-ft` scripts
- DAS
- Signed
* Enables developers to run FT locally
> build: Use new FT structure

- .github/workflows/cd.yml
- .github/workflows/review-approved.yml
- Makefile
- Pipfile
- Pipfile.lock
- docker-compose-aws.yml
- docker-compose.yml
- docs/source/devel/index.rst
- docs/source/devel/repository_service_tuf_worker.services.storage.rst
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/__init__.py
- repository_service_tuf_worker/services/__init__.py
- repository_service_tuf_worker/services/storage/__init__.py
- repository_service_tuf_worker/services/storage/awss3.py
- requirements-dev.txt
- requirements.txt
- tests/files/aws/init-services.sh
- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
- tests/unit/tuf_repository_service_worker/services/storage/conftest.py
- tests/unit/tuf_repository_service_worker/services/storage/test_awss3.py
- tests/unit/tuf_repository_service_worker/test__init__.py
- Add boto3 to use AWS services
- Add awswrangler to parse objects in the bucket
- Add localstack to enable a development in the docker-compose.yml
- Add localstack-init in Makefile to enable developers to initiate the
services configuration
It uses the official `boto3` library for AWS Sessions, Client and
Resources and also the `awswrangler` to query the AWS S3 metadata.
It implements all the unit tests covering 100% coverage.
Updates the RSTUF Worker documentation adding a better format for
Storage Backend and KeyVault Backend.
> AWS S3 Storage Backend Service implementation

- .github/workflows/cd.yml
fix: CD requires set-component-versions to be triggered by tag
It also creates the correct dependencies between jobs.
> fix: CD requires set-component-versions to be trigger by tag

- repository_service_tuf_worker/interfaces.py
- repository_service_tuf_worker/services/keyvault/local.py
- repository_service_tuf_worker/services/storage/awss3.py
- repository_service_tuf_worker/services/storage/local.py
- tests/unit/conftest.py
- tests/unit/tuf_repository_service_worker/services/keyvault/test_local.py
- tests/unit/tuf_repository_service_worker/services/storage/test_awss3.py
- tests/unit/tuf_repository_service_worker/services/storage/test_local.py
- tests/unit/tuf_repository_service_worker/test_interfaces.py
Fixes #401 
Transform the I(KeyVault|Storage).cofigure as factory method meaning
it will be used as a constructor.
This will allow removing duplicating code from `__init__` or `configure`.
Additionally, I used the opportunity to remove the "kwargs" variable
and operations inside interfaces._setup_service_dynaconf() as we
don't use it for anything. 
As a continuation, I was able also to remove
ServerSettings.argument field from ServerSettings as again it was not
used anywhere any more.
Finally, I used `configure` as a constructor to remove the calls
of `_raw_key_parser` inside `LocalKeyVault.get()` as the result
of those calls will be the same during the container's lifetime.
> Use I(KeyVault|Storage).cofigure as factory method 

- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
This change is required after the following CLI commit was merged: 
https://github.com/repository-service-tuf/repository-service-tuf-cli/commit/d2e066eaee2f7986aa7994a5c57d7a8cd4ade3c3
Signed-off-by: Martin Vrachev <mvrachev@vmware.com
> Rename CLI argument in ft-tests scripts

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
related to #336
Implement support for distributed asynchronous root metadata signging in the course of a "metadata update" event.
Other than the already supported "bootstrap" signing event, signatures added to root during "metadata update" must validate with keys from trusted OR new root, and meet the signature threshold of trusted AND new root.
*Related changes:*
- Refactor `_validate_{signature, threshold}` helpers to accept an optional delegator (e.g. trusted root).
- Add `_sign_result` helper to return a "sign metadata"-specific task result.
> Support 'metadata update' in 'sign_metadata' task

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
The TRUSTED_ROOT repository setting will be used by RSTUF API when composing the 
`GET /api/v1/metadata/sign response`.
Connected: https://github.com/repository-service-tuf/repository-service-tuf-api/pull/499
> Save `TRUSTED_ROOT` repository setting 

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
The goal of the "update_snapshot" refactoring is to:
1. make a better separation between the two usages of "update_snapshot"
- the first is to update snapshot and all roles that were given with the "targets_roles" argument
- the second is to update snapshot and ALL bin target roles In the end, I wanted to be able to call "update_snapshot" with "bump_all" without having to pass the "targets_roles" argument.
2. fix a bug where when calling "update_snapshot" the resulting new snapshot meta didn't contain updated information for targets.json This resulted in a bug that when calling "_run_online_roles_bump", which updated targets.json, we saved the new targets.json, but the new snapshot.json didn't reference it.
The second part of this refactoring is about "_run_online_roles_bump". Again there …
> Refactor update_snapshot & _run_online_roles_bump

- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/signer.py
- tests/unit/tuf_repository_service_worker/test_repository.py
- tests/unit/tuf_repository_service_worker/test_signer.py
This PR allows starting the worker without key vault configuration. Unlike a previous attempt (#441), it does not change any specific key vault initialisation code, but instead skips key vault initialisation altogether, if the configuration is not provided.
In addition, the repository is updated to retrieve signers from a newly added signer store, instead of calling the key vault directly. Under the hood, the signer store does use the existing key vault, but only when needed. Moreover, this design makes it easier to provide a meaningful error message about missing config, again, only when needed.
Also note that in the future the signer store can easily be extended to fetch signers from other locations, e.g. URIs provided via public key metadata.
See commits for details!
> Do not require key vault at start up time

- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/signer.py
- tests/unit/tuf_repository_service_worker/test_signer.py
The custom FileNameSigner is similar to the previously registered CryptoSigner provided by securesystemslib, with the following differences:
- uri format is `fn:<file name>`
- a base path for the key in `<file name>` must be provided via environment variable `RSTUF_ONLINE_KEY_DIR`
- only **unencrypted** keys are supported
supersedes #427
> Add FileNameSigner and register in SignerStore

- docker-compose-aws.yml
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/services/storage/awss3.py
- repository_service_tuf_worker/signer.py
- tests/files/aws/init-kms.sh
- tests/unit/tuf_repository_service_worker/services/storage/test_awss3.py
- tests/unit/tuf_repository_service_worker/test_signer.py
- tox.ini
*[EDIT 02/14/24: remove poc/draft status]* 
Add AWS KMS support to SignerStore and test with localstack (`tox -e local-aws-kms`)
**Change details**
* Whitelist required ambient settings in SignerStore (see tox.ini for required settings)
* Add independent tox environment to init/cleanup localstack, configure ambient AWS KMS credentials, create a test key, and run the test.
* Add test to "import" test public key from AWS KMS and configure private key URI - this would typically happen in a key management UI (e.g. RSTUF CLI) - and use `SignerStore.get` to load the signer.
**Todo**
This PR adds a single unit test method, which is ran against a 3rd party service. This doesn't fit into the current test architecture, where 3rd party services are consistently mocked in unit tests, and only …
> Add AWS KMS support to SignerStore

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Fixes #438 
Add support for custom delegated targets which could be used by PyPI and other of our users.
This will allow for greater flexibility and we could support special use cases for bigger users.
Note: it's related to pr https://github.com/repository-service-tuf/repository-service-tuf-api/pull/542. When testing use both this and the API pr.
> Add support for custom delegated targets

- .github/workflows/functional-tests.yml
- Makefile
- tests/functional/scripts/run-ft-das.sh
- tests/functional/scripts/run-ft-signed.sh
- Split (fast) tests into 3 jobs
- Put slow tests in a separate job. If we start storing the test durations
we won't need to do that probably.
Related to https://github.com/repository-service-tuf/repository-service-tuf/pull/603
> Split test running in CI

- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/models/targets/models.py
- repository_service_tuf_worker/models/targets/schemas.py
- repository_service_tuf_worker/repository.py
- tests/unit/conftest.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test_repository.py
The specification defines `datetime` as UTC time zone:
https://theupdateframework.github.io/specification/latest/#file-formats-date-time
The python-tuf project updated all their datetime objects,  so it's time we do it now as well.
I updated everywhere to replace `datetime.utc()` to `datetime.now(timezone.utc)`
as `datetime.utc()`  is documented for
deprecation and is officially deprecated from python 12:
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
Also, I added to all `datetime.now()` calls the argument `timezone.utc` to make sure that
we are consistent with python-tuf as python-tuf did that change as well: https://github.com/theupdateframework/python-tuf/pull/2573
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
> Force UTC timezone for all datetime objects

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Instead of loading targets and iterating through all its target roles
I saved the delegated roles in a Redis environment for quick and
shorter retrieval.
Additionally, inside `_run_online_roles_bump` I load `targets` only when we need it.
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
> Optimize custom target delegation retrieval 

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Add support for force online metadata update
Signed-off-by: Martin Vrachev <martin.vrachev@broadcom.com>
> Add support for force online metadata update

- Makefile
- README.rst
If we are not running Functional Tests on GH
actions we don't run the tests in different groups.
Related to https://github.com/repository-service-tuf/repository-service-tuf/pull/684
> Add case for local running of FT tests from Makefile

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
In this pr I address two bugs and one refactoring:
1. Don't persist root if the online roles bump fails. This makes sure that the root is stored last when all online roles are bumped.
2. Give a `trusted_root_update()` with a more telling name. As we don't update trusted root with `_trusted_root_update()` and this makes the function name misleading.
3.  Fix: update the delegation key when bumping targets. Strangely, we forgot to change the key referenced in top level targets role when bumping targets with an online key change. This caused a bug that was reported: https://github.com/repository-service-tuf/repository-service-tuf-worker/issues/491
Fixes #491
> Fix two bugs & do a small refactoring

- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
Fixes #503 
Fix a bug which happened when we wanted to bump targets and a custom
delegated role at the same time which caused a bump of the target role
and all custom delegated roles at the same time.
**Note**: Merge #501 first.
> Fix force md update with custom delegations

- .github/workflows/functional-tests.yml
We don't need to run FT-DAS-SLOW and FT-SIGNED-SLOW.
The FT SLOW, which runs the functional tests for Performance.
The functional tests for performances are related to adding/removing targets and are not affected by the DAS/Signed process
> tests: Remove FT Signed SLOW

- alembic/versions/4b8d450e8360_initial_version.py
- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/models/targets/models.py
- repository_service_tuf_worker/repository.py
- repository_service_tuf_worker/services/storage/awss3.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test_repository.py
It starts with a simple fix in the Database Schema:
- Include rolename as unique to avoid duplications
- Include column to set Target Role as active
- Implement several CRUD to handle inactive roles
Implements the Custom Delegation Roles
- Add support to custom delegation roles during bootstrap
- Add support for using offline and online keys in the custom delegations roles
- Add support for adding extra delegation roles afterwards
- Add support for updating delegation roles
- Add support for deleting delegation roles
TODO:
We will prioritize the functions tests (FT) for this feature, preventing regrations or breaking compatibility with BINS.
We will implement unit tests to improve the development process.
[Functional Tests without breaking BINS …
> feat: Custom Delegation(Target) Roles

- supervisor-dev.conf
- supervisor.conf
It fixes the celery hotname instance.
We use this hostname to check the livenessprobe and readninessprobe in the helm charts.
https://github.com/repository-service-tuf/helm-charts/blob/176fa84eed2ed34a7ce22eabf7469425fdb42881/charts/rstuf-worker/values.yaml#L12
[skip slow]
> fix: celery hostname for the instance

- .github/workflows/review-approved.yml
- docker-compose-aws.yml
- docker-compose-redis.yml
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/repository.py
- tests/unit/tuf_repository_service_worker/test_repository.py
- remove deprecated code previously announced
- add note in the documentation for MySQL/MariaDB support
- disable tests for MySQL/MariaDB
> Remove deprecated and warn users for MySQL/MariaDB

- repository_service_tuf_worker/repository.py
Performance improvement: Use threads to create all delegated roles
Before : Added 2048 hash bins in 119.36732602119446 seconds
Current: Added 2048 hash bins in 1.8565280437469482 seconds
PyPI (PEP 458) and RubyGems size creation:
Added 16384 hash bins in 15.13554310798645 seconds
> perf: improve bootstrap performance hash bins

- alembic/versions/1effe827d0cd_initial_db.py
- app.py
- docs/source/guide/Docker_README.md
- repository_service_tuf_worker/models/targets/crud.py
- repository_service_tuf_worker/models/targets/models.py
- repository_service_tuf_worker/models/targets/schemas.py
- repository_service_tuf_worker/repository.py
- tests/unit/test_app.py
- tests/unit/tuf_repository_service_worker/models/targets/test_crud.py
- tests/unit/tuf_repository_service_worker/test_repository.py
RSTUF right now has an issue if used the backend storage (TUF metadata) as S3 buckets with large number of delegations roles (example hash bins).
The problem starts with 512 delegation roles and above and it needs to update a large number delegation roles (bump online roles) at the same time.
An example, 2048 roles can tack ~60 min to update it. Usually it will fail due the timeout.
Use Celery Chain to create multiple tasks that can be distributed to Workers|
In that PR we propose the use of Celery groups by using chunk feature and create a Chain.
Based in the above example it can bump 2048 roles in ~360 seconds (6 min) without hanging
> perf: fix bump online roles

- .github/dependabot.yml
It will help maintainers to review and merge dependabot for GHA as the Functional Tests is quite expensive in time.
> build: group dependenbot gha PRs

- Dockerfile
Container Image dev tag is broken
fix the container image startup with supervisor.conf not found
```
│ /usr/local/lib/python3.13/site-packages/pydantic/_internal/_config.py:373: UserWarning: Valid config keys have changed in V2:                    │
│ * 'orm_mode' has been renamed to 'from_attributes'                                                                                               │
│   warnings.warn(message, UserWarning)                                                                                                            │
│ INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.                                                                                   │
│ INFO  [alembic.runtime.migration] Will assume transactional DDL. …
```
> hotfix: fix container image startup supervisor

- .readthedocs.yaml
read the docs doesn't support Pipenv directly
> docs: fix the readthedocs build

- Makefile
help developers to get commands (public) instructions by running `make`
```shell
❯ make
Makefile commands:
build-dev                      Build the dev image
run-dev                        Run the development environment
db-migration                   Run a database migration
stop                           Stop the development environment
clean                          Clean up the development environment
purge                          Purge the development environment
reformat                       Reformat the code using black and isort
tests                          Run the tests
coverage                       Run the tests with coverage
docs                           Build the documentation
precommit                      install and run pre-commit hooks
help …
```
> docs: add help for make

- docker-compose-aws.yml
- docker-compose-mysql.yml
- docker-compose-redis.yml
- docker-compose.yml
* Postress 15.1 to 17.5
Both have the same vulnerability scores and none of the other images have a lower vulnerability score.
* redis 4.0 to 8.0
The 4.0 image had vulnerabilities while the 8.0 doesn't have any vulnerabilities until now.
> Updated the Docker images

- tests/unit/tuf_repository_service_worker/test_repository.py
Add unit tests to functions in repository.py to improve code coverage.
This PR adds tests for the following functions:
- get_delegation_keyids
- bump_persist_role
- update_targets_delegated_role
- metadata_delegation - test case for delete, error, update and invalid action
- sign_metadata - test case for non root role
> tests: Add unit tests to repository functions
